MODEL:
  CONFIG: {}
  PRECISION: bfloat16
  TYPE: predictor
  WEIGHTS: models/predictor
NUM_GPUS: 4
PIPELINE:
  MODULES: {}
  TYPE: longscape_train_predictor
RNG_SEED: 3
SOLVER:
  ACCUM_STEPS: 1
  ADAM_BETA2: 0.95
  BASE_LR: 0.0001
  DECAY_GAMMA: 0.5
  DECAY_STEPS: []
  DISPLAY: 20
  LR_POLICY: 
  MAX_STEPS: 1000
  MIN_LR: 0.0
  OPTIMIZER: AdamW
  SNAPSHOT_EVERY: 10000
  SNAPSHOT_PREFIX: model
  WARM_UP_FACTOR: 0.001
  WARM_UP_STEPS: 1000
  WEIGHT_DECAY: 0.02
TRAIN:
  BATCH_SIZE: 16
  CHECKPOINTING: 2
  DATASET: cache/predictor
  DATASET2:
  LOADER: vae_train
  NUM_THREADS: 8